Repository cypht-org/cypht, pull requests merged in 2024-11, with the labels that each got.

#1316 [FIX].env.example: DISABLE_ORIGIN_CHECK assigns twice
  .env.example
Labels: needsCherryPicksTo2.x

#1317 [FIX]DEFAULT_TEXT_ONLY value must be false
  .env.example
  config/app.php
  lib/environment.php
Labels: needsCherryPicksTo2.x

#1331 make sieve data format automatic on connect
  modules/imap/functions.php
  modules/nux/modules.php
  modules/sievefilters/functions.php
  modules/sievefilters/hm-sieve.php
  modules/sievefilters/modules.php
Labels: urgent

#1389 refactor(workflow): pr title validation update
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.lint.pr.yml
Labels: refactor
